### ISSUE TITLE
Support configuration and changing of the browser window size and position

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#101]
Set Browser resolution:

  "maximiseBrowser": false,
  "browserX":0,
  "browserY":0,
  "browserWidth":1080,
  "browserHeight":768,

Set res to command
set pos to command

https://stackoverflow.com/questions/15397483/how-do-i-set-browser-width-and-height-in-selenium-webdriver

--------------------------------

Build: 
Pickle Application : 1.17.0.4
Pickle Core : 1.17.0.4
Pickle Automation : 1.17.0.4
Pickle Console : 1.0.0.0
Build Architecture: Amd64
When: 04/10/2022 07:31 UTC
.Net #: Above version 4.7.1 [528372] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit

**Comment by ThinkingEngine-net** [comment]
- [ ] 1.  Add config parameters. (defaults (0,0 and 800x600)
- [ ] 2. Add toggle to enable (disable by default)
- [ ] 3. Verify config file creation and input
- [ ] 4. Limit x,y parameter to >=0
- [ ] 5. Limit Width & Height to >=50 (min size 50x50)
- [ ] 6. Add to execution window config.
- [ ] 7. Add logic that maximise window overrides sizing.
- [ ] 8. Build compatibility for chrome initialisation
- [ ] 9. Build compatibility for edge initialisation
- [ ] 10. Build compatibility for firefox initialisation
- [ ] 11. Add the statement "Given I move the browser to x,y (dumb action no validation) - all browsers?
- [ ] 12. Add the statement "Given I resize the browser to width,height (dumb action no validation) -all browsers?
- [ ] Update documentation

**Comment by ThinkingEngine-net** [comment]
Tested.

All documentation updated:

- https://te-wiki.marescal.co.uk/doku.php?id=wiki:pickle:windowsize
- https://te-wiki.marescal.co.uk/doku.php?id=wiki:pickle:sautomconfig#configuration_parameters
- https://te-wiki.marescal.co.uk/doku.php?id=wiki:pickle:supported_statements#window_management
