### ISSUE TITLE
Support for mouse buttons

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#102]
I would like Pickle TS ....
Requirement  to automate right mouse click and access the functions from the pop-up menu, scheduling a component date/time via a calendar applet

(CG) 

--------------------------------

Build: 
Pickle Application : 1.17.0.4
Pickle Core : 1.17.0.4
Pickle Automation : 1.17.0.4
Pickle Console : 1.0.0.0
Build Architecture: Amd64
When: 06/10/2022 07:47 UTC
.Net #: Above version 4.7.1 [528372] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit

**Comment by ThinkingEngine-net** [comment]
Added, also added DoubleClick.
