### ISSUE TITLE
Version of XLS library misaligned (Pickle Error Captured)

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#103]
Build: 
Pickle Application : 1.17.0.4
Pickle Core : 1.17.0.4
Pickle Automation : 1.17.0.4
Pickle Console : 1.0.0.0
Build Architecture: Amd64
When: 03/11/2022 09:27 UTC
.Net #: Above version 4.7.1 [528372] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit
Memory Available: 24292MB
CPU Used: 0%

 --------------- Error Stack Trace --------------
   at pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   at pickle.frmResults.ExportAsSheets(String fileName)
   at pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   at pickle.frmPickle.mnuSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 ---------------End Stack Trace --------------

 --------------- Error Handler Stack Trace --------------
[0] GetExecutingStackTrace at offset 73 in file:line:column <filename unknown>:0:0

[1] setError at offset 1398 in file:line:column <filename unknown>:0:0

[2] ReportError at offset 50 in file:line:column <filename unknown>:0:0

[3] Application_ThreadException at offset 28 in file:line:column <filename unknown>:0:0

[4] OnThreadException at offset 168 in file:line:column <filename unknown>:0:0

[5] WndProcException at offset 28 in file:line:column <filename unknown>:0:0

[6] Callback at offset 194 in file:line:column <filename unknown>:0:0

[7] DispatchMessageW at offset 0 in file:line:column <filename unknown>:0:0

[8] DispatchMessageW at offset 0 in file:line:column <filename unknown>:0:0

[9] System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop at offset 833 in file:line:column <filename unknown>:0:0

[10] RunMessageLoopInner at offset 455 in file:line:column <filename unknown>:0:0

[11] RunMessageLoop at offset 82 in file:line:column <filename unknown>:0:0

[12] Main at offset 237 in file:line:column <filename unknown>:0:0

 ---------------End Stack Trace --------------

 --------------- Location --------------

 Target: Void ExportResultsAsSheets(System.String)
 Where: pickle.core
 ---------------End Location --------------

 --------------- Error --------------
System.IO.FileLoadException: Could not load file or assembly "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89" or one of its dependencies. The located assembly"s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: "Syncfusion.XlsIO.Base, Version=20.1450.0.55, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89"
   at pickle.core.testCycle.ExportResultsAsSheets(String FileName)
   at pickle.frmResults.ExportAsSheets(String fileName)
   at pickle.frmPickle.mnuSaveAs_Click(Object sender, EventArgs e)
   at pickle.frmPickle.mnuSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

 ---------------End Error --------------

 --------------- Active Source --------------
{"Name":"Single Script - 01_01_10_ManualCommandsEm","Description":"","ID":"b6745a35-c8f0-4a31-95a0-4eb57410c957","Scripts":[{"projectRelativePath":"","type":0,"lastGoodCompileCheckSum":"","CompileStatus":4,"GherkinCompileStatus":4,"lastError":"","rule":0,"Condition":"","CMDParams":"","CMD":"","ID":"1a4a97b3-13e6-43a2-aeae-828cbb63422b","InheritVars":true,"parent":"","Name":"01_01_10_ManualCommandsEm","isNew":true,"cmdRegExpSuccess":"","browser":0,"customBrowserName":"Chrome"}]}

## Applies to: Cimbali Macchina Super-automatica S20

Feature: Manual Commands
            In this menu, technician can actuate all the motors and the solonoid valves which are present
            in the machine. This can be dependent on the machine configuration.
  
    # Milk solenoid valve Em:
    # This solenoid valve is present on the left side of the machine
    # Log command:
        # verification of the correct command
    # Continuity:
        # Position black tip of multimeter GND
        # Position red tip of multimeter on pin 19 of J6 connector
    # Voltage measurement:
        # Position black tip of multimeter on left terminal of Em
        # Position red tip of multimeter on right terminal of Em
    # Current measurement:
        # current clamp on Em wire
    # Visual and auditory validation:
        # Em label becomes green during activation
        # Machine dispense milk from milk delivery spout
        
    Background: 
        Given       Machine is equipped with Em solenoid valve
            And     Milk dispenser is connected to machine
        
    Scenario: Manual Commands - Em not actuated - visual inspection
        Given       Technician is in Manual Commands menu
        When        Technician scrolls the list of actuable body part until Em
        Then        Em label is selected in body_scrolling widget
            And     Em solenoid valve is not actuated
            And     Dot on the right of Em label is coloured in grey
            And     Sensor values are not changed
            And     Labels inside body_matrix have not diffirent colour
    
    Scenario: Manual Commands - Em not actuated - voltage measurement
        Given       Technician is in Manual Commands menu
            And     Em solenoid valve is selected in body_scrolling widget
        When        Em solenoid valve is not actuated
            And     Validator positions multimeter"s tip on Em terminals
        Then        Validator measures 0V on Em terminals
      
    Scenario: Manual Commands - Em not actuated - current measurement
        Given       Technician is in Manual Commands menu
            And     Em solenoid valve is selected in body_scrolling widget
        When        Em solenoid valve is not actuated
            And     Validator positions current clamp on Em wire (pin 19 of J6)
        Then        Validator measures current as specific
            
    Scenario: Manual Commands - Em not actuated - continuity
        Given       Technician is in Manual Commands menu
            And     Em solenoid valve is selected in body_scrolling widget
        When        Em solenoid valve is not actuated
            And     Validator verifies continuity on pin 19 of J6
        Then        Multimeter does not beep
            
    Scenario: Manual Commands - Em actuated - visual inspection
        Given       Technician is in Manual Commands menu
            And     single_activation button is highlighted
            And     Em label is selected in body_scrolling widget
            And     Em solenoid valve is not actuated
        When        Technician press and hold Em label
        Then        Em solenoid valve is actuated
            And     Dot on the right of Em label is coloured in green
            And     Sensor values does not change
            And     Em label inside body_matrix is coloured in green
            
    Scenario: Manual Commands - Em actuated - Extraction of command log
        Given       Technician is in Manual Commands menu
            And     Validator has connected serial debug port of PC Slave board to PC
            And     Em solenoid valve is selected in body_scrolling widget
        When        Em solenoid valve is actuated
        Then        Em Command log from PC Slave board in testing is correctly retrieved
            
    Scenario: Manual Commands - Em actuated - Command log comparison
        Given       Em command log from PC Slave board in testing is correctly retrieved 
            And     Em command log from Original PC Slave board are available
        When        Command logs are compared
        Then        Command logs comparison is successful
    
    Scenario: Manual Commands - Em actuated - voltage measurement
        Given       Technician is in Manual Commands menu
            And     Em solenoid valve is selected in body_scrolling widget
        When        Em solenoid valve is actuated
            And     Validator positions multimeter"s tip on Em terminals
        Then        Validator measures 24V on Em terminals
        
    Scenario: Manual Commands - Em actuated - current measurement
        Given       Technician is in Manual Commands menu
            And     Em solenoid valve is selected in body_scrolling widget
        When        Em solenoid valve is actuated
            And     Validator positions current clamp on Em wire (pin 19 of J6)
        Then        Validator measures current as specific
    
    Scenario: Manual Commands - Em actuated - continuity
        Given       Technician is in Manual Commands menu
            And     Em solenoid valve is selected in body_scrolling widget
        When        Em solenoid valve is actuated
            And     Validator verifies continuity on pin 19 of J6
        Then        Multimeter beeps
        
    Scenario: Manual Commands - Stop actuating Em - visual inspection
        Given       Technician is in Manual Commands menu
            And     single_activation button is highlighted
            And     Em solenoid valve is actuated
        When        Technician stops pressing Em label in body_scrolling widget
        Then        Em solenoid valve is not actuated
            And     Machine stops dispensing milk from milk delivery spout
            And     Dot on the right of Em label is coloured in grey
            And     Sensor values are not changed
            And     Em label inside body_matrix is coloured in grey
            
    Scenario: Manual Commands - Stop actuating Em - Extraction of command log
        Given       Technician is in Manual Commands menu
            And     Validator has connected serial debug port of PC Slave board to PC
            And     Em solenoid valve is actuated
        When        Technician stops actuating Em solenoid valve
        Then        Em Command log from PC Slave board in testing is correctly retrieved
            
    Scenario: Manual Commands - Stop actuating Em - Command log comparison
        Given       Em command log from PC Slave board in testing is correctly retrieved 
            And     Em command log from Original PC Slave board are available
        When        Command logs are compared
        Then        Command logs comparison is successful
    
    Scenario: Manual Commands - Stop actuating Em - voltage measurement
        Given       Technician is in Manual Commands menu
        When        Technician stops actuating Em solenoid valve
            And     Validator positions multimeter"s tip on Em terminals
        Then        Validator measures 0V
        
    Scenario: Manual Commands - Stop actuating Em - current measurement
        Given       Technician is in Manual Commands menu
        When        Technician stops actuating Em solenoid valve
            And     Validator positions current clamp on Em wire (pin 19 of J6)
        Then        Validator measures current as specific
        
    Scenario: Manual Commands - Stop actuating Em - continuity
        Given       Technician is in Manual Commands menu
            And     Em solenoid valve is selected in body_scrolling widget
        When        Em solenoid valve is not actuated
            And     Validator verifies continuity on pin 19 of J6
        Then        Multimeter does not beep
 --------------- Active Source --------------

**Comment by ThinkingEngine-net** [comment]
Verified that it should have been 1460.0.55.  Correct when libraries are updated.

![image](https://github.com/ThinkingEngine-net/PickleTestSuite/assets/15537950/56d781c5-505c-4a6e-9e1d-0e42ba927864)

**Comment by ThinkingEngine-net** [comment]
Fixed:

![image](https://github.com/user-attachments/assets/4dfe023d-0fdc-42b9-9c09-866464fe0592)
