### ISSUE TITLE
Generate unique alphabetic value

### ISSUE THREAD

**Issue by sskcg** [ThinkingEngine-net/PickleTestSuite#40]
When I use -> "Given I record a unique alphabetic value to <field-name>", the value generated is a combination of upper case and lowercase alphabets. Some fields like "username" accept only lower case alphabets. so generating unique alphabetic value in lowercase is not possible at the moment.

Thanks,
Shalini.

**Comment by ThinkingEngine-net** [comment]
Added through #31
