### ISSUE TITLE
Browser Maximise

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#53]
Is there an statement to max the broswer window when running an automation script. 
Currently at the moment I am unable to use the scroll command as what I am selecting is left hand side of the screen.

--------------------------------

Build: 
Pickle Application : Unknown
Pickle Core : Unknown
Pickle Automation : Unknown
Pickle Console : Unknown
Build Architecture: Amd64
When: 23/12/2020 11:38 UTC
.Net #: Above version 4.7.1 [528372] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit

**Comment by ThinkingEngine-net** [comment]
The function is supported in the configuration for executing a test:

![image](https://user-images.githubusercontent.com/15537950/115104260-252ef800-9f4f-11eb-9120-aeef335f4907.png)

It is also possible to configure it as the default through the execution config file.  See https://te-wiki.marescal.co.uk/doku.php?id=wiki:pickle:sautomconfig#configuration_parameters.

**Comment by ThinkingEngine-net** [comment]
Added article - https://thinkingengine.marescal.co.uk/2021/04/17/how-to-how-do-i-maximise-the-browser/
