### ISSUE TITLE
Add window maximise to standard statements

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#56]
I would like Pickle TS ....

 to add a statement to maximise browser: driver.manage().window().maximize();

--------------------------------

Build: 
Pickle Application : 1.15.0.0
Pickle Core : 1.15.0.0
Pickle Automation : 1.15.0.0
Pickle Console : 1.0.0.0
Build Architecture: Amd64
When: 28-07-2021 08:55 UTC
.Net #: Above version 4.7.1 [528372] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit

**Comment by ThinkingEngine-net** [comment]
Added and unit tested.

Feature: Unit Test : Windows

@javascript
  Scenario: First Scenario
    Given I go to "http://www.google.com"
    And I minimise the browser
    Then the browser should be minimised
    And I maximise the browser
    Then the browser should be maximised
    And I make the browser fullscreen
    Then the browser should be FullScreen
