### ISSUE TITLE
Create a  mechanism for encrypting text and then using it securely in scripts

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#60]
Create a standard encryption mechanism (not unique keys). The purpose is to better masked passwords from other users.

- New menu to encrypt a sting
- Ability to declare a static variable as encrypted.
- Decrypt static variable when executing string
- Display encrypted version all output unless debug is enabled.

--------------------------------
I would like Pickle TS ....

For passwords security we can use something to encrypt or decrypt our passwords

--------------------------------

Build: 
Pickle Application : 1.16.0.1
Pickle Core : 1.16.0.0
Pickle Automation : 1.16.0.0
Pickle Console : 1.0.0.0
Build Architecture: Amd64
When: 05-08-2021 07:22 UTC
.Net #: Above version 4.7.1 [528372] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit

**Comment by ThinkingEngine-net** [comment]
Added menu (edit Menu) item to obfuscate and new comment #obsfuscate.
