### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#67]
I would like Pickle TS ....

Please check the below code for Drag and drop. This works for me 

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import io.github.bonigarcia.wdm.WebDriverManager;

public class DragAndDropConcept {

public static void main(String[] args) {

WebDriverManager.chromedriver().setup();
		
WebDriver driver = new ChromeDriver();
		
driver.get(https://jqueryui.com/resources/demos/droppable/default.html);
		
WebElement sourceEle = driver.findElement(By.id("draggable"));
WebElement targetEle = driver.findElement(By.id("droppable"));
		
Actions act = new Actions(driver);
//act.clickAndHold(sourceEle).moveToElement(targetEle).release(targetEle).build().perform();

(or)

//act.dragAndDrop(sourceEle, targetEle).perform();

--------------------------------

Build: 
Pickle Application : 1.17.0.1
Pickle Core : 1.17.0.1
Pickle Automation : 1.17.0.1
Pickle Console : 1.0.0.0
Build Architecture: Amd64
When: 17-08-2021 10:54 UTC
.Net #: Above version 4.7.1 [528372] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit

**Comment by ThinkingEngine-net** [comment]
Drag and dop are not working in Selenium currently. Actions fail.

**Comment by ThinkingEngine-net** [comment]
All seem to be working as of selenium upgrade.
