### ISSUE TITLE
Pickle Portable detection not working

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#72]
Installed pickle TS shows as portable.

--------------------------------

Build: 
Pickle Application : 1.17.0.2
Pickle Core : 1.17.0.2
Pickle Automation : 1.17.0.2
Pickle Console : 1.0.0.0
Build Architecture: Amd64
When: 21/09/2021 06:44 UTC
.Net #: Above version 4.7.1 [528040] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit

**Comment by ThinkingEngine-net** [comment]
Fixed.
