### ISSUE TITLE
Wait statement should be available even when browser automation is not required,

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#73]
Make "And I wait for 5 seconds" a calculated statement, so  @javascript is not required.

--------------------------------

Build: 
Pickle Application : Unknown
Pickle Core : Unknown
Pickle Automation : Unknown
Pickle Console : Unknown
Build Architecture: Amd64
When: 24/09/2021 07:36 UTC
.Net #: Above version 4.7.1 [528040] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit

**Comment by ThinkingEngine-net** [comment]
Wait currently required @javascript (i/e/ browser automation) to execute.  There is no reason for this and it stops the ability to issue wait statements in none automated tests.

**Comment by ThinkingEngine-net** [comment]
Fixed.
