### ISSUE TITLE
Variables can only be defined within a scenario.

### ISSUE THREAD

**Issue by support-thinkingengine** [ThinkingEngine-net/PickleTestSuite#74]
Can only define variables within a scenario.

--------------------------------

Build: 
Pickle Application : 1.17.0.2
Pickle Core : 1.17.0.2
Pickle Automation : 1.17.0.2
Pickle Console : 1.0.0.0
Build Architecture: Amd64
When: 01/10/2021 07:33 UTC
.Net #: Above version 4.7.1 [528040] - 4.0.30319.42000
OS #: Microsoft Windows NT 6.2.9200.0
OS Architecture: 64 bit

**Comment by ThinkingEngine-net** [comment]
Cannot Replicate it.  Test Case:

![image](https://user-images.githubusercontent.com/15537950/169655743-db33fea7-0364-46a8-a1d8-1f85c99f523e.png)

results:

![image](https://user-images.githubusercontent.com/15537950/169655768-f7ab9f04-c828-4ae1-9518-1167412d2fbc.png)
